// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module controller_print_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        uart_xmit_fifo_din,
        uart_xmit_fifo_full_n,
        uart_xmit_fifo_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] uart_xmit_fifo_din;
input   uart_xmit_fifo_full_n;
output   uart_xmit_fifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] uart_xmit_fifo_din;
reg uart_xmit_fifo_write;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] p_str_4_address0;
reg    p_str_4_ce0;
wire   [7:0] p_str_4_q0;
reg    uart_xmit_fifo_blk_n;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln341_fu_313_p2;
wire   [0:0] icmp_ln343_fu_325_p2;
wire    ap_CS_fsm_state3;
wire   [6:0] trunc_ln22_fu_194_p1;
wire    ap_CS_fsm_state4;
wire   [6:0] trunc_ln41_fu_203_p1;
wire    ap_CS_fsm_state7;
reg   [0:0] tmp_reg_354;
reg   [6:0] trunc_ln22_reg_378;
reg   [6:0] trunc_ln41_reg_387;
wire   [0:0] icmp_ln73_fu_294_p2;
wire   [0:0] tmp_fu_174_p3;
wire    ap_CS_fsm_state2;
wire   [7:0] input_count_4_fu_182_p2;
reg   [7:0] input_count_4_reg_358;
reg   [63:0] grp_load_fu_156_p1;
reg   [63:0] fmt_assign_load_4_reg_363;
wire   [63:0] add_ln60_fu_188_p2;
reg   [63:0] add_ln60_reg_373;
wire   [0:0] icmp_ln64_fu_221_p2;
reg   [0:0] icmp_ln64_reg_397;
wire    ap_CS_fsm_state5;
wire   [1:0] add_ln13_fu_227_p2;
reg   [1:0] add_ln13_reg_401;
wire   [63:0] add_ln13_2_fu_242_p2;
reg   [63:0] add_ln13_2_reg_406;
reg   [63:0] fmt_assign_load11_reg_419;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln66_fu_284_p2;
wire   [2:0] p_str_4_addr_3_gep_fu_126_p3;
wire   [1:0] i_9_fu_319_p2;
reg    ap_predicate_op96_write_state8;
reg    ap_predicate_op98_write_state8;
reg    ap_block_state8;
reg   [1:0] i_6_reg_134;
reg    ap_block_state4;
reg   [1:0] i_reg_145;
reg    ap_predicate_op31_write_state3;
reg    ap_block_state3;
reg   [7:0] input_count_fu_74;
reg    ap_predicate_op81_write_state7;
reg    ap_block_state7;
reg   [63:0] fmt_assign_fu_78;
wire   [63:0] add_ln76_fu_299_p2;
wire   [63:0] add_ln69_2_fu_263_p2;
wire   [63:0] add_ln43_fu_207_p2;
reg   [63:0] ap_sig_allocacmp_fmt_assign_load11;
reg   [1:0] i_8_fu_82;
wire   [63:0] zext_ln13_fu_238_p1;
wire   [2:0] zext_ln69_fu_249_p1;
wire   [2:0] add_ln69_fu_253_p2;
wire   [63:0] zext_ln69_2_fu_259_p1;
wire   [6:0] trunc_ln66_fu_274_p1;
wire   [6:0] add_ln66_fu_278_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

controller_print_2_p_str_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
p_str_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str_4_address0),
    .ce0(p_str_4_ce0),
    .q0(p_str_4_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        fmt_assign_fu_78 <= 64'd0;
    end else if ((~(trunc_ln22_fu_194_p1 == 7'd37) & ~(trunc_ln22_fu_194_p1 == 7'd10) & ~(trunc_ln22_fu_194_p1 == 7'd0) & ~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3))) begin
        fmt_assign_fu_78 <= add_ln60_fu_188_p2;
    end else if ((~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_203_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4))) begin
        fmt_assign_fu_78 <= add_ln43_fu_207_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_221_p2 == 1'd1))) begin
        fmt_assign_fu_78 <= add_ln69_2_fu_263_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_284_p2 == 1'd1) & (icmp_ln64_reg_397 == 1'd0))) begin
        fmt_assign_fu_78 <= add_ln13_2_reg_406;
    end else if ((~(trunc_ln41_reg_387 == 7'd37) & ~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & ~(trunc_ln41_reg_387 == 7'd0) & (trunc_ln22_reg_378 == 7'd37) & (tmp_reg_354 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln73_fu_294_p2 == 1'd0))) begin
        fmt_assign_fu_78 <= add_ln76_fu_299_p2;
    end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (icmp_ln341_fu_313_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        fmt_assign_fu_78 <= add_ln60_reg_373;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_fu_203_p1 == 7'd0) & ~(trunc_ln41_fu_203_p1 == 7'd37) & ~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
        i_6_reg_134 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_284_p2 == 1'd0) & (icmp_ln64_reg_397 == 1'd0))) begin
        i_6_reg_134 <= add_ln13_reg_401;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (icmp_ln341_fu_313_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        i_reg_145 <= i_9_fu_319_p2;
    end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (trunc_ln22_fu_194_p1 == 7'd10) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_145 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        input_count_fu_74 <= 8'd0;
    end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & ((((~(trunc_ln22_reg_378 == 7'd0) & (trunc_ln41_reg_387 == 7'd37) & (tmp_reg_354 == 1'd0)) | (~(trunc_ln22_reg_378 == 7'd0) & ~(trunc_ln41_reg_387 == 7'd0) & (tmp_reg_354 == 1'd0) & (icmp_ln73_fu_294_p2 == 1'd0))) | (~(trunc_ln22_reg_378 == 7'd37) & ~(trunc_ln22_reg_378 == 7'd0) & (tmp_reg_354 == 1'd0))) | (~(trunc_ln22_reg_378 == 7'd0) & (trunc_ln22_reg_378 == 7'd10) & (tmp_reg_354 == 1'd0))))) begin
        input_count_fu_74 <= input_count_4_reg_358;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_221_p2 == 1'd0))) begin
        add_ln13_2_reg_406 <= add_ln13_2_fu_242_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln13_reg_401 <= add_ln13_fu_227_p2;
        i_8_fu_82 <= i_6_reg_134;
        icmp_ln64_reg_397 <= icmp_ln64_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln60_reg_373 <= add_ln60_fu_188_p2;
        trunc_ln22_reg_378 <= trunc_ln22_fu_194_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln66_fu_284_p2 == 1'd1) | (icmp_ln64_reg_397 == 1'd1)))) begin
        fmt_assign_load11_reg_419 <= grp_load_fu_156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_174_p3 == 1'd0))) begin
        fmt_assign_load_4_reg_363 <= grp_load_fu_156_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_count_4_reg_358 <= input_count_4_fu_182_p2;
        tmp_reg_354 <= input_count_fu_74[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln41_reg_387 <= trunc_ln41_fu_203_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0)))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1)))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & ((tmp_reg_354 == 1'd1) | ((trunc_ln22_reg_378 == 7'd0) | ((~(trunc_ln41_reg_387 == 7'd37) & (trunc_ln22_reg_378 == 7'd37) & (icmp_ln73_fu_294_p2 == 1'd1)) | (~(trunc_ln41_reg_387 == 7'd37) & (trunc_ln41_reg_387 == 7'd0) & (trunc_ln22_reg_378 == 7'd37)))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & ((tmp_reg_354 == 1'd1) | ((trunc_ln22_reg_378 == 7'd0) | ((~(trunc_ln41_reg_387 == 7'd37) & (trunc_ln22_reg_378 == 7'd37) & (icmp_ln73_fu_294_p2 == 1'd1)) | (~(trunc_ln41_reg_387 == 7'd37) & (trunc_ln41_reg_387 == 7'd0) & (trunc_ln22_reg_378 == 7'd37))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_284_p2 == 1'd1) & (icmp_ln64_reg_397 == 1'd0))) begin
        ap_sig_allocacmp_fmt_assign_load11 = add_ln13_2_reg_406;
    end else begin
        ap_sig_allocacmp_fmt_assign_load11 = fmt_assign_fu_78;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln66_fu_284_p2 == 1'd1) | (icmp_ln64_reg_397 == 1'd1)))) begin
        grp_load_fu_156_p1 = ap_sig_allocacmp_fmt_assign_load11;
    end else if ((((trunc_ln41_fu_203_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_221_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_221_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (tmp_fu_174_p3 == 1'd0)))) begin
        grp_load_fu_156_p1 = fmt_assign_fu_78;
    end else begin
        grp_load_fu_156_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_str_4_address0 = p_str_4_addr_3_gep_fu_126_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_str_4_address0 = add_ln13_2_fu_242_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_str_4_address0 = add_ln60_fu_188_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_str_4_address0 = grp_load_fu_156_p1;
    end else begin
        p_str_4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3)))) begin
        p_str_4_ce0 = 1'b1;
    end else begin
        p_str_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln41_fu_203_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)) | (~(trunc_ln22_fu_194_p1 == 7'd37) & ~(trunc_ln22_fu_194_p1 == 7'd10) & ~(trunc_ln22_fu_194_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln343_fu_325_p2 == 1'd1) & (icmp_ln341_fu_313_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)) | ((icmp_ln343_fu_325_p2 == 1'd0) & (icmp_ln341_fu_313_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)) | (~(trunc_ln41_reg_387 == 7'd37) & ~(trunc_ln41_reg_387 == 7'd0) & (trunc_ln22_reg_378 == 7'd37) & (tmp_reg_354 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln73_fu_294_p2 == 1'd0)))) begin
        uart_xmit_fifo_blk_n = uart_xmit_fifo_full_n;
    end else begin
        uart_xmit_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (1'b1 == ap_CS_fsm_state8) & (ap_predicate_op98_write_state8 == 1'b1))) begin
        uart_xmit_fifo_din = 8'd10;
    end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (1'b1 == ap_CS_fsm_state8) & (ap_predicate_op96_write_state8 == 1'b1))) begin
        uart_xmit_fifo_din = 8'd13;
    end else if (((~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_203_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4)) | (~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_203_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)))) begin
        uart_xmit_fifo_din = 8'd37;
    end else if (((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & (ap_predicate_op81_write_state7 == 1'b1)) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3) & (ap_predicate_op31_write_state3 == 1'b1)))) begin
        uart_xmit_fifo_din = p_str_4_q0;
    end else begin
        uart_xmit_fifo_din = 'bx;
    end
end

always @ (*) begin
    if (((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & (ap_predicate_op81_write_state7 == 1'b1)) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3) & (ap_predicate_op31_write_state3 == 1'b1)) | (~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_203_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4)) | (~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_203_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (1'b1 == ap_CS_fsm_state8) & (ap_predicate_op98_write_state8 == 1'b1)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (1'b1 == ap_CS_fsm_state8) & (ap_predicate_op96_write_state8 == 1'b1)))) begin
        uart_xmit_fifo_write = 1'b1;
    end else begin
        uart_xmit_fifo_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_174_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (trunc_ln22_fu_194_p1 == 7'd10) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~(trunc_ln22_fu_194_p1 == 7'd37) & ~(trunc_ln22_fu_194_p1 == 7'd10) & ~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1)) & (trunc_ln22_fu_194_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~(trunc_ln41_fu_203_p1 == 7'd0) & ~(trunc_ln41_fu_203_p1 == 7'd37) & ~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~(((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4) & ((trunc_ln41_fu_203_p1 == 7'd37) | (trunc_ln41_fu_203_p1 == 7'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln66_fu_284_p2 == 1'd1) | (icmp_ln64_reg_397 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & ((tmp_reg_354 == 1'd1) | ((trunc_ln22_reg_378 == 7'd0) | ((~(trunc_ln41_reg_387 == 7'd37) & (trunc_ln22_reg_378 == 7'd37) & (icmp_ln73_fu_294_p2 == 1'd1)) | (~(trunc_ln41_reg_387 == 7'd37) & (trunc_ln41_reg_387 == 7'd0) & (trunc_ln22_reg_378 == 7'd37))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1)) & (1'b1 == ap_CS_fsm_state7) & ((((~(trunc_ln22_reg_378 == 7'd0) & (trunc_ln41_reg_387 == 7'd37) & (tmp_reg_354 == 1'd0)) | (~(trunc_ln22_reg_378 == 7'd0) & ~(trunc_ln41_reg_387 == 7'd0) & (tmp_reg_354 == 1'd0) & (icmp_ln73_fu_294_p2 == 1'd0))) | (~(trunc_ln22_reg_378 == 7'd37) & ~(trunc_ln22_reg_378 == 7'd0) & (tmp_reg_354 == 1'd0))) | (~(trunc_ln22_reg_378 == 7'd0) & (trunc_ln22_reg_378 == 7'd10) & (tmp_reg_354 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (icmp_ln341_fu_313_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1))) & (icmp_ln341_fu_313_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_2_fu_242_p2 = (zext_ln13_fu_238_p1 + grp_load_fu_156_p1);

assign add_ln13_fu_227_p2 = (i_6_reg_134 + 2'd1);

assign add_ln43_fu_207_p2 = (grp_load_fu_156_p1 + 64'd2);

assign add_ln60_fu_188_p2 = (fmt_assign_load_4_reg_363 + 64'd1);

assign add_ln66_fu_278_p2 = ($signed(trunc_ln66_fu_274_p1) + $signed(7'd80));

assign add_ln69_2_fu_263_p2 = (grp_load_fu_156_p1 + zext_ln69_2_fu_259_p1);

assign add_ln69_fu_253_p2 = (zext_ln69_fu_249_p1 + 3'd2);

assign add_ln76_fu_299_p2 = (fmt_assign_load11_reg_419 + 64'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state3 = ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op31_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4 = (((trunc_ln41_fu_203_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_203_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7 = ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op81_write_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state8 = (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op98_write_state8 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op96_write_state8 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op31_write_state3 = (~(trunc_ln22_fu_194_p1 == 7'd37) & ~(trunc_ln22_fu_194_p1 == 7'd10) & ~(trunc_ln22_fu_194_p1 == 7'd0));
end

always @ (*) begin
    ap_predicate_op81_write_state7 = (~(trunc_ln41_reg_387 == 7'd37) & ~(trunc_ln41_reg_387 == 7'd0) & (trunc_ln22_reg_378 == 7'd37) & (tmp_reg_354 == 1'd0) & (icmp_ln73_fu_294_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op96_write_state8 = ((icmp_ln343_fu_325_p2 == 1'd0) & (icmp_ln341_fu_313_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op98_write_state8 = ((icmp_ln343_fu_325_p2 == 1'd1) & (icmp_ln341_fu_313_p2 == 1'd0));
end

assign i_9_fu_319_p2 = (i_reg_145 + 2'd1);

assign icmp_ln341_fu_313_p2 = ((i_reg_145 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln343_fu_325_p2 = ((i_reg_145 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_221_p2 = ((i_6_reg_134 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_284_p2 = ((add_ln66_fu_278_p2 > 7'd9) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_294_p2 = ((fmt_assign_load11_reg_419 == 64'd4) ? 1'b1 : 1'b0);

assign input_count_4_fu_182_p2 = (input_count_fu_74 + 8'd1);

assign p_str_4_addr_3_gep_fu_126_p3 = grp_load_fu_156_p1;

assign tmp_fu_174_p3 = input_count_fu_74[32'd7];

assign trunc_ln22_fu_194_p1 = p_str_4_q0[6:0];

assign trunc_ln41_fu_203_p1 = p_str_4_q0[6:0];

assign trunc_ln66_fu_274_p1 = p_str_4_q0[6:0];

assign zext_ln13_fu_238_p1 = add_ln13_fu_227_p2;

assign zext_ln69_2_fu_259_p1 = add_ln69_fu_253_p2;

assign zext_ln69_fu_249_p1 = i_8_fu_82;

endmodule //controller_print_2
