// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module controller_print_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v0,
        uart_xmit_fifo_din,
        uart_xmit_fifo_full_n,
        uart_xmit_fifo_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [4:0] v0;
output  [7:0] uart_xmit_fifo_din;
input   uart_xmit_fifo_full_n;
output   uart_xmit_fifo_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] uart_xmit_fifo_din;
reg uart_xmit_fifo_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] p_str_2_address0;
reg    p_str_2_ce0;
wire   [7:0] p_str_2_q0;
reg    uart_xmit_fifo_blk_n;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln341_fu_580_p2;
wire   [0:0] icmp_ln343_fu_592_p2;
wire    ap_CS_fsm_state3;
wire   [6:0] trunc_ln22_fu_299_p1;
wire    ap_CS_fsm_state4;
wire   [6:0] trunc_ln41_fu_308_p1;
wire    ap_CS_fsm_state7;
reg   [0:0] tmp_4_reg_640;
reg   [6:0] trunc_ln22_reg_664;
reg   [6:0] trunc_ln41_reg_673;
wire   [0:0] icmp_ln73_fu_429_p2;
wire   [6:0] trunc_ln73_fu_425_p1;
wire   [31:0] v0_cast_fu_257_p1;
reg   [31:0] v0_cast_reg_632;
wire   [0:0] tmp_4_fu_279_p3;
wire    ap_CS_fsm_state2;
wire   [7:0] input_count_6_fu_287_p2;
reg   [7:0] input_count_6_reg_644;
reg   [63:0] grp_load_fu_243_p1;
reg   [63:0] fmt_assign_load22_reg_649;
wire   [63:0] add_ln60_fu_293_p2;
reg   [63:0] add_ln60_reg_659;
wire   [0:0] icmp_ln64_fu_326_p2;
reg   [0:0] icmp_ln64_reg_683;
wire    ap_CS_fsm_state5;
wire   [1:0] add_ln13_fu_332_p2;
reg   [1:0] add_ln13_reg_687;
wire   [63:0] add_ln13_3_fu_347_p2;
reg   [63:0] add_ln13_3_reg_692;
wire   [7:0] width_1_fu_415_p2;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln66_fu_385_p2;
reg   [63:0] fmt_assign_load23_reg_710;
wire   [3:0] p_str_2_addr_3_gep_fu_172_p3;
reg   [6:0] trunc_ln73_reg_721;
wire   [63:0] add_ln76_fu_434_p2;
reg   [63:0] add_ln76_reg_728;
wire   [31:0] tmp_3_fu_443_p6;
reg   [31:0] tmp_3_reg_733;
wire   [31:0] tmp_1_fu_493_p6;
reg   [31:0] tmp_1_reg_738;
wire   [31:0] tmp_fu_516_p6;
reg   [31:0] tmp_reg_743;
wire   [1:0] i_11_fu_586_p2;
reg    ap_predicate_op148_write_state9;
reg    ap_predicate_op150_write_state9;
reg    ap_block_state9;
wire    grp_write_hex_fu_214_ap_start;
wire    grp_write_hex_fu_214_ap_done;
wire    grp_write_hex_fu_214_ap_idle;
wire    grp_write_hex_fu_214_ap_ready;
wire   [7:0] grp_write_hex_fu_214_uart_xmit_fifo_din;
wire    grp_write_hex_fu_214_uart_xmit_fifo_write;
wire    grp_write_dec_fu_229_ap_start;
wire    grp_write_dec_fu_229_ap_done;
wire    grp_write_dec_fu_229_ap_idle;
wire    grp_write_dec_fu_229_ap_ready;
reg   [31:0] grp_write_dec_fu_229_value_r;
reg   [0:0] grp_write_dec_fu_229_is_signed;
wire   [7:0] grp_write_dec_fu_229_uart_xmit_fifo_din;
wire    grp_write_dec_fu_229_uart_xmit_fifo_write;
reg   [1:0] i_8_reg_180;
reg    ap_block_state4;
reg   [7:0] width_reg_191;
reg   [1:0] i_reg_203;
reg    ap_predicate_op36_write_state3;
reg    ap_block_state3;
reg    grp_write_hex_fu_214_ap_start_reg;
reg    ap_predicate_op104_write_state7;
reg    ap_predicate_op119_write_state7;
reg    ap_block_state7_ignore_call4;
wire    ap_CS_fsm_state8;
reg    grp_write_dec_fu_229_ap_start_reg;
reg   [7:0] input_count_fu_110;
reg    ap_predicate_op123_call_state8;
reg    ap_predicate_op125_call_state8;
reg    ap_predicate_op127_call_state8;
reg    ap_block_state8_on_subcall_done;
reg   [63:0] fmt_assign_fu_114;
wire   [63:0] add_ln69_3_fu_368_p2;
wire   [63:0] add_ln43_fu_312_p2;
reg   [63:0] ap_sig_allocacmp_fmt_assign_load23;
reg   [7:0] value_index_1_fu_118;
wire   [7:0] zext_ln13_1_fu_563_p1;
wire   [7:0] grp_fu_251_p2;
reg    ap_block_state7;
reg   [1:0] i_10_fu_122;
wire   [7:0] c_4_fu_479_p1;
wire   [63:0] zext_ln13_fu_343_p1;
wire   [2:0] zext_ln69_fu_354_p1;
wire   [2:0] add_ln69_fu_358_p2;
wire   [63:0] zext_ln69_3_fu_364_p1;
wire   [7:0] add_ln66_fu_379_p2;
wire   [7:0] empty_28_fu_391_p2;
wire   [7:0] empty_29_fu_397_p2;
wire   [7:0] add_ln68_1_fu_409_p2;
wire   [7:0] add_ln68_fu_403_p2;
wire   [1:0] tmp_3_fu_443_p5;
wire   [1:0] tmp_2_fu_466_p5;
wire   [31:0] tmp_2_fu_466_p6;
wire   [1:0] tmp_1_fu_493_p5;
wire   [1:0] tmp_fu_516_p5;
wire   [5:0] tmp_5_fu_539_p4;
wire   [0:0] icmp_ln108_fu_549_p2;
wire   [1:0] trunc_ln13_fu_535_p1;
wire   [1:0] value_index_6_fu_555_p3;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_condition_311;
reg    ap_condition_317;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_write_hex_fu_214_ap_start_reg = 1'b0;
#0 grp_write_dec_fu_229_ap_start_reg = 1'b0;
end

controller_print_1_p_str_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_str_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str_2_address0),
    .ce0(p_str_2_ce0),
    .q0(p_str_2_q0)
);

controller_write_hex grp_write_hex_fu_214(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_hex_fu_214_ap_start),
    .ap_done(grp_write_hex_fu_214_ap_done),
    .ap_idle(grp_write_hex_fu_214_ap_idle),
    .ap_ready(grp_write_hex_fu_214_ap_ready),
    .value_r(tmp_3_reg_733),
    .zero_fill(1'd0),
    .uppercase(1'd1),
    .width(width_reg_191),
    .uart_xmit_fifo_din(grp_write_hex_fu_214_uart_xmit_fifo_din),
    .uart_xmit_fifo_full_n(uart_xmit_fifo_full_n),
    .uart_xmit_fifo_write(grp_write_hex_fu_214_uart_xmit_fifo_write)
);

controller_write_dec grp_write_dec_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_dec_fu_229_ap_start),
    .ap_done(grp_write_dec_fu_229_ap_done),
    .ap_idle(grp_write_dec_fu_229_ap_idle),
    .ap_ready(grp_write_dec_fu_229_ap_ready),
    .value_r(grp_write_dec_fu_229_value_r),
    .is_signed(grp_write_dec_fu_229_is_signed),
    .width(width_reg_191),
    .uart_xmit_fifo_din(grp_write_dec_fu_229_uart_xmit_fifo_din),
    .uart_xmit_fifo_full_n(uart_xmit_fifo_full_n),
    .uart_xmit_fifo_write(grp_write_dec_fu_229_uart_xmit_fifo_write)
);

controller_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U23(
    .din0(v0_cast_reg_632),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(tmp_3_fu_443_p5),
    .dout(tmp_3_fu_443_p6)
);

controller_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U24(
    .din0(v0_cast_reg_632),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(tmp_2_fu_466_p5),
    .dout(tmp_2_fu_466_p6)
);

controller_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U25(
    .din0(v0_cast_reg_632),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(tmp_1_fu_493_p5),
    .dout(tmp_1_fu_493_p6)
);

controller_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U26(
    .din0(v0_cast_reg_632),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(tmp_fu_516_p5),
    .dout(tmp_fu_516_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_dec_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if (((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (1'b1 == ap_CS_fsm_state7) & ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd105) & (icmp_ln73_fu_429_p2 == 1'd0)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd100) & (icmp_ln73_fu_429_p2 == 1'd0)))) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd117) & (icmp_ln73_fu_429_p2 == 1'd0)))) begin
            grp_write_dec_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_write_dec_fu_229_ap_ready == 1'b1)) begin
            grp_write_dec_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_hex_fu_214_ap_start_reg <= 1'b0;
    end else begin
        if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd88) & (icmp_ln73_fu_429_p2 == 1'd0))) begin
            grp_write_hex_fu_214_ap_start_reg <= 1'b1;
        end else if ((grp_write_hex_fu_214_ap_ready == 1'b1)) begin
            grp_write_hex_fu_214_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        fmt_assign_fu_114 <= 64'd0;
    end else if ((~(trunc_ln22_fu_299_p1 == 7'd37) & ~(trunc_ln22_fu_299_p1 == 7'd10) & ~(trunc_ln22_fu_299_p1 == 7'd0) & ~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3))) begin
        fmt_assign_fu_114 <= add_ln60_fu_293_p2;
    end else if ((~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4))) begin
        fmt_assign_fu_114 <= add_ln43_fu_312_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_326_p2 == 1'd1))) begin
        fmt_assign_fu_114 <= add_ln69_3_fu_368_p2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_385_p2 == 1'd1) & (icmp_ln64_reg_683 == 1'd0))) begin
        fmt_assign_fu_114 <= add_ln13_3_reg_692;
    end else if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        fmt_assign_fu_114 <= add_ln76_reg_728;
    end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (icmp_ln341_fu_580_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        fmt_assign_fu_114 <= add_ln60_reg_659;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_fu_308_p1 == 7'd0) & ~(trunc_ln41_fu_308_p1 == 7'd37) & ~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
        i_8_reg_180 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_385_p2 == 1'd0) & (icmp_ln64_reg_683 == 1'd0))) begin
        i_8_reg_180 <= add_ln13_reg_687;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (icmp_ln341_fu_580_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        i_reg_203 <= i_11_fu_586_p2;
    end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (trunc_ln22_fu_299_p1 == 7'd10) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_203 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        input_count_fu_110 <= 8'd0;
    end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((((~(trunc_ln22_reg_664 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd0)) | (~(trunc_ln22_reg_664 == 7'd0) & (trunc_ln41_reg_673 == 7'd37))) | (~(trunc_ln22_reg_664 == 7'd37) & ~(trunc_ln22_reg_664 == 7'd0))) | (~(trunc_ln22_reg_664 == 7'd0) & (trunc_ln22_reg_664 == 7'd10))))) begin
        input_count_fu_110 <= input_count_6_reg_644;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        value_index_1_fu_118 <= 8'd0;
    end else if (((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (1'b1 == ap_CS_fsm_state7) & ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd105) & (icmp_ln73_fu_429_p2 == 1'd0)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd100) & (icmp_ln73_fu_429_p2 == 1'd0)))) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd88) & (icmp_ln73_fu_429_p2 == 1'd0)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd117) & (icmp_ln73_fu_429_p2 == 1'd0)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd99) & (icmp_ln73_fu_429_p2 == 1'd0)))) begin
        value_index_1_fu_118 <= grp_fu_251_p2;
    end else if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        value_index_1_fu_118 <= zext_ln13_1_fu_563_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_fu_308_p1 == 7'd0) & ~(trunc_ln41_fu_308_p1 == 7'd37) & ~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
        width_reg_191 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_385_p2 == 1'd0) & (icmp_ln64_reg_683 == 1'd0))) begin
        width_reg_191 <= width_1_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_326_p2 == 1'd0))) begin
        add_ln13_3_reg_692 <= add_ln13_3_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln13_reg_687 <= add_ln13_fu_332_p2;
        i_10_fu_122 <= i_8_reg_180;
        icmp_ln64_reg_683 <= icmp_ln64_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln60_reg_659 <= add_ln60_fu_293_p2;
        trunc_ln22_reg_664 <= trunc_ln22_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln73_fu_429_p2 == 1'd0))) begin
        add_ln76_reg_728 <= add_ln76_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_4_fu_279_p3 == 1'd0))) begin
        fmt_assign_load22_reg_649 <= grp_load_fu_243_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln66_fu_385_p2 == 1'd1) | (icmp_ln64_reg_683 == 1'd1)))) begin
        fmt_assign_load23_reg_710 <= grp_load_fu_243_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_count_6_reg_644 <= input_count_6_fu_287_p2;
        tmp_4_reg_640 <= input_count_fu_110[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd117) & (icmp_ln73_fu_429_p2 == 1'd0))) begin
        tmp_1_reg_738 <= tmp_1_fu_493_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd88) & (icmp_ln73_fu_429_p2 == 1'd0))) begin
        tmp_3_reg_733 <= tmp_3_fu_443_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd105) & (icmp_ln73_fu_429_p2 == 1'd0)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd100) & (icmp_ln73_fu_429_p2 == 1'd0))))) begin
        tmp_reg_743 <= tmp_fu_516_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln41_reg_673 <= trunc_ln41_fu_308_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        trunc_ln73_reg_721 <= trunc_ln73_fu_425_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        v0_cast_reg_632[4 : 0] <= v0_cast_fu_257_p1[4 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0)))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1)))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1)))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (1'b1 == ap_CS_fsm_state7) & ((tmp_4_reg_640 == 1'd1) | ((trunc_ln22_reg_664 == 7'd0) | ((~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (icmp_ln73_fu_429_p2 == 1'd1)) | (~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln41_reg_673 == 7'd0)))))) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (1'b1 == ap_CS_fsm_state7) & ((tmp_4_reg_640 == 1'd1) | ((trunc_ln22_reg_664 == 7'd0) | ((~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (icmp_ln73_fu_429_p2 == 1'd1)) | (~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln41_reg_673 == 7'd0))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln66_fu_385_p2 == 1'd1) & (icmp_ln64_reg_683 == 1'd0))) begin
        ap_sig_allocacmp_fmt_assign_load23 = add_ln13_3_reg_692;
    end else begin
        ap_sig_allocacmp_fmt_assign_load23 = fmt_assign_fu_114;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln66_fu_385_p2 == 1'd1) | (icmp_ln64_reg_683 == 1'd1)))) begin
        grp_load_fu_243_p1 = ap_sig_allocacmp_fmt_assign_load23;
    end else if ((((trunc_ln41_fu_308_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_326_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln64_fu_326_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (tmp_4_fu_279_p3 == 1'd0)))) begin
        grp_load_fu_243_p1 = fmt_assign_fu_114;
    end else begin
        grp_load_fu_243_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if ((1'b1 == ap_condition_317)) begin
            grp_write_dec_fu_229_is_signed = 1'd1;
        end else if ((1'b1 == ap_condition_311)) begin
            grp_write_dec_fu_229_is_signed = 1'd0;
        end else begin
            grp_write_dec_fu_229_is_signed = 'bx;
        end
    end else begin
        grp_write_dec_fu_229_is_signed = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if ((1'b1 == ap_condition_317)) begin
            grp_write_dec_fu_229_value_r = tmp_reg_743;
        end else if ((1'b1 == ap_condition_311)) begin
            grp_write_dec_fu_229_value_r = tmp_1_reg_738;
        end else begin
            grp_write_dec_fu_229_value_r = 'bx;
        end
    end else begin
        grp_write_dec_fu_229_value_r = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_str_2_address0 = p_str_2_addr_3_gep_fu_172_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_str_2_address0 = add_ln13_3_fu_347_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_str_2_address0 = add_ln60_fu_293_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        p_str_2_address0 = grp_load_fu_243_p1;
    end else begin
        p_str_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3)))) begin
        p_str_2_ce0 = 1'b1;
    end else begin
        p_str_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((trunc_ln41_fu_308_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)) | (~(trunc_ln22_fu_299_p1 == 7'd37) & ~(trunc_ln22_fu_299_p1 == 7'd10) & ~(trunc_ln22_fu_299_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln343_fu_592_p2 == 1'd1) & (icmp_ln341_fu_580_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | ((icmp_ln343_fu_592_p2 == 1'd0) & (icmp_ln341_fu_580_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9)) | (~(trunc_ln73_fu_425_p1 == 7'd88) & ~(trunc_ln73_fu_425_p1 == 7'd117) & ~(trunc_ln73_fu_425_p1 == 7'd105) & ~(trunc_ln73_fu_425_p1 == 7'd100) & ~(trunc_ln73_fu_425_p1 == 7'd99) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln73_fu_429_p2 == 1'd0)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (trunc_ln73_fu_425_p1 == 7'd99) & (icmp_ln73_fu_429_p2 == 1'd0)))) begin
        uart_xmit_fifo_blk_n = uart_xmit_fifo_full_n;
    end else begin
        uart_xmit_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (ap_predicate_op150_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        uart_xmit_fifo_din = 8'd10;
    end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (ap_predicate_op148_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        uart_xmit_fifo_din = 8'd13;
    end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (ap_predicate_op104_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        uart_xmit_fifo_din = c_4_fu_479_p1;
    end else if (((~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4)) | (~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)))) begin
        uart_xmit_fifo_din = 8'd37;
    end else if (((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (ap_predicate_op119_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (ap_predicate_op36_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        uart_xmit_fifo_din = p_str_2_q0;
    end else if ((((1'b1 == ap_CS_fsm_state8) & ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd100)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd105)))) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (1'b1 == ap_CS_fsm_state8) & (trunc_ln73_reg_721 == 7'd117)))) begin
        uart_xmit_fifo_din = grp_write_dec_fu_229_uart_xmit_fifo_din;
    end else if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (1'b1 == ap_CS_fsm_state8) & (trunc_ln73_reg_721 == 7'd88))) begin
        uart_xmit_fifo_din = grp_write_hex_fu_214_uart_xmit_fifo_din;
    end else begin
        uart_xmit_fifo_din = grp_write_dec_fu_229_uart_xmit_fifo_din;
    end
end

always @ (*) begin
    if (((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (ap_predicate_op119_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (ap_predicate_op104_write_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | (~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (ap_predicate_op36_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4)) | (~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (ap_predicate_op150_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | (~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (ap_predicate_op148_write_state9 == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        uart_xmit_fifo_write = 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state8) & ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd100)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd105)))) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (1'b1 == ap_CS_fsm_state8) & (trunc_ln73_reg_721 == 7'd117)))) begin
        uart_xmit_fifo_write = grp_write_dec_fu_229_uart_xmit_fifo_write;
    end else if ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (1'b1 == ap_CS_fsm_state8) & (trunc_ln73_reg_721 == 7'd88))) begin
        uart_xmit_fifo_write = grp_write_hex_fu_214_uart_xmit_fifo_write;
    end else begin
        uart_xmit_fifo_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_4_fu_279_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~(trunc_ln22_fu_299_p1 == 7'd37) & ~(trunc_ln22_fu_299_p1 == 7'd10) & ~(trunc_ln22_fu_299_p1 == 7'd0) & ~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (trunc_ln22_fu_299_p1 == 7'd10) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (trunc_ln22_fu_299_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1)) & (trunc_ln22_fu_299_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~(trunc_ln41_fu_308_p1 == 7'd0) & ~(trunc_ln41_fu_308_p1 == 7'd37) & ~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~(((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0))) & (trunc_ln41_fu_308_p1 == 7'd37) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln66_fu_385_p2 == 1'd1) | (icmp_ln64_reg_683 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & (1'b1 == ap_CS_fsm_state7) & ((tmp_4_reg_640 == 1'd1) | ((trunc_ln22_reg_664 == 7'd0) | ((~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (icmp_ln73_fu_429_p2 == 1'd1)) | (~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln41_reg_673 == 7'd0))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1))) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln73_fu_429_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & ((((~(trunc_ln22_reg_664 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd0)) | (~(trunc_ln22_reg_664 == 7'd0) & (trunc_ln41_reg_673 == 7'd37))) | (~(trunc_ln22_reg_664 == 7'd37) & ~(trunc_ln22_reg_664 == 7'd0))) | (~(trunc_ln22_reg_664 == 7'd0) & (trunc_ln22_reg_664 == 7'd10))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (icmp_ln341_fu_580_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~(((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1))) & (icmp_ln341_fu_580_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_3_fu_347_p2 = (zext_ln13_fu_343_p1 + grp_load_fu_243_p1);

assign add_ln13_fu_332_p2 = (i_8_reg_180 + 2'd1);

assign add_ln43_fu_312_p2 = (grp_load_fu_243_p1 + 64'd2);

assign add_ln60_fu_293_p2 = (fmt_assign_load22_reg_649 + 64'd1);

assign add_ln66_fu_379_p2 = ($signed(p_str_2_q0) + $signed(8'd208));

assign add_ln68_1_fu_409_p2 = ($signed(empty_29_fu_397_p2) + $signed(8'd208));

assign add_ln68_fu_403_p2 = (p_str_2_q0 + empty_28_fu_391_p2);

assign add_ln69_3_fu_368_p2 = (grp_load_fu_243_p1 + zext_ln69_3_fu_364_p1);

assign add_ln69_fu_358_p2 = (zext_ln69_fu_354_p1 + 3'd2);

assign add_ln76_fu_434_p2 = (fmt_assign_load23_reg_710 + 64'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3 = ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op36_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4 = (((trunc_ln41_fu_308_p1 == 7'd0) & (uart_xmit_fifo_full_n == 1'b0)) | ((trunc_ln41_fu_308_p1 == 7'd37) & (uart_xmit_fifo_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7 = (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1)));
end

always @ (*) begin
    ap_block_state7_ignore_call4 = (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op119_write_state7 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op104_write_state7 == 1'b1)));
end

always @ (*) begin
    ap_block_state8_on_subcall_done = (((ap_predicate_op127_call_state8 == 1'b1) & (grp_write_dec_fu_229_ap_done == 1'b0)) | ((ap_predicate_op125_call_state8 == 1'b1) & (grp_write_dec_fu_229_ap_done == 1'b0)) | ((ap_predicate_op123_call_state8 == 1'b1) & (grp_write_hex_fu_214_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state9 = (((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op150_write_state9 == 1'b1)) | ((uart_xmit_fifo_full_n == 1'b0) & (ap_predicate_op148_write_state9 == 1'b1)));
end

always @ (*) begin
    ap_condition_311 = (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd117));
end

always @ (*) begin
    ap_condition_317 = ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd100)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd105)));
end

always @ (*) begin
    ap_predicate_op104_write_state7 = (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (trunc_ln73_fu_425_p1 == 7'd99) & (icmp_ln73_fu_429_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op119_write_state7 = (~(trunc_ln73_fu_425_p1 == 7'd88) & ~(trunc_ln73_fu_425_p1 == 7'd117) & ~(trunc_ln73_fu_425_p1 == 7'd105) & ~(trunc_ln73_fu_425_p1 == 7'd100) & ~(trunc_ln73_fu_425_p1 == 7'd99) & ~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (tmp_4_reg_640 == 1'd0) & (icmp_ln73_fu_429_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op123_call_state8 = (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd88));
end

always @ (*) begin
    ap_predicate_op125_call_state8 = (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd117));
end

always @ (*) begin
    ap_predicate_op127_call_state8 = ((~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd100)) | (~(trunc_ln41_reg_673 == 7'd0) & ~(trunc_ln41_reg_673 == 7'd37) & (trunc_ln22_reg_664 == 7'd37) & (trunc_ln73_reg_721 == 7'd105)));
end

always @ (*) begin
    ap_predicate_op148_write_state9 = ((icmp_ln343_fu_592_p2 == 1'd0) & (icmp_ln341_fu_580_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_write_state9 = ((icmp_ln343_fu_592_p2 == 1'd1) & (icmp_ln341_fu_580_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op36_write_state3 = (~(trunc_ln22_fu_299_p1 == 7'd37) & ~(trunc_ln22_fu_299_p1 == 7'd10) & ~(trunc_ln22_fu_299_p1 == 7'd0));
end

assign c_4_fu_479_p1 = tmp_2_fu_466_p6[7:0];

assign empty_28_fu_391_p2 = width_reg_191 << 8'd3;

assign empty_29_fu_397_p2 = width_reg_191 << 8'd1;

assign grp_fu_251_p2 = (value_index_1_fu_118 + 8'd1);

assign grp_write_dec_fu_229_ap_start = grp_write_dec_fu_229_ap_start_reg;

assign grp_write_hex_fu_214_ap_start = grp_write_hex_fu_214_ap_start_reg;

assign i_11_fu_586_p2 = (i_reg_203 + 2'd1);

assign icmp_ln108_fu_549_p2 = ((tmp_5_fu_539_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln341_fu_580_p2 = ((i_reg_203 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln343_fu_592_p2 = ((i_reg_203 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_326_p2 = ((i_8_reg_180 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_385_p2 = ((add_ln66_fu_379_p2 > 8'd9) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_429_p2 = ((fmt_assign_load23_reg_710 == 64'd15) ? 1'b1 : 1'b0);

assign input_count_6_fu_287_p2 = (input_count_fu_110 + 8'd1);

assign p_str_2_addr_3_gep_fu_172_p3 = grp_load_fu_243_p1;

assign tmp_1_fu_493_p5 = value_index_1_fu_118[1:0];

assign tmp_2_fu_466_p5 = value_index_1_fu_118[1:0];

assign tmp_3_fu_443_p5 = value_index_1_fu_118[1:0];

assign tmp_4_fu_279_p3 = input_count_fu_110[32'd7];

assign tmp_5_fu_539_p4 = {{value_index_1_fu_118[7:2]}};

assign tmp_fu_516_p5 = value_index_1_fu_118[1:0];

assign trunc_ln13_fu_535_p1 = value_index_1_fu_118[1:0];

assign trunc_ln22_fu_299_p1 = p_str_2_q0[6:0];

assign trunc_ln41_fu_308_p1 = p_str_2_q0[6:0];

assign trunc_ln73_fu_425_p1 = p_str_2_q0[6:0];

assign v0_cast_fu_257_p1 = v0;

assign value_index_6_fu_555_p3 = ((icmp_ln108_fu_549_p2[0:0] == 1'b1) ? 2'd3 : trunc_ln13_fu_535_p1);

assign width_1_fu_415_p2 = (add_ln68_1_fu_409_p2 + add_ln68_fu_403_p2);

assign zext_ln13_1_fu_563_p1 = value_index_6_fu_555_p3;

assign zext_ln13_fu_343_p1 = add_ln13_fu_332_p2;

assign zext_ln69_3_fu_364_p1 = add_ln69_fu_358_p2;

assign zext_ln69_fu_354_p1 = i_10_fu_122;

always @ (posedge ap_clk) begin
    v0_cast_reg_632[31:5] <= 27'b000000000000000000000000000;
end

endmodule //controller_print_1
